##
## Makefile for Makefile in /home/pacaud_j/rendu/PSU/PSU_2014_minishell2/lib
## 
## Made by Jean-Baptiste Pacaud-Paris
## Login   <pacaud_j@epitech.net>
## 
## Started on  Sat Mar  7 16:24:32 2015 Jean-Baptiste Pacaud-Paris
## Last update Sat Mar  7 16:25:08 2015 Jean-Baptiste Pacaud-Paris
##

all:
	cc -c *.c ; ar -rc libmy.a *.o
